### ISSUE TITLE
[feature request] Specify custom resolvers to be used

### ISSUE THREAD

**Issue by viict** [docker-flow/docker-flow-proxy#1]
**Description**

How can we specify resolvers to the haproxy? Not the docker resolver.

Just to understand our use case:
We have a few dynamic hostnames that periodically changes their IP, if we don't set a few resolvers with the "hold" option haproxy does not handle traffic to the correct IP.

I've found the DO_NOT_RESOLVE_ADDR but I think it's not what we are looking for.

**Additional information you deem important (e.g. issue happens only occasionally):**

Just to let you know our use case, is something like this, and for this example I used the public internet dns servers we know. But, we use a private dns cluster there.

```
resolvers dns
	nameserver dns-0  4.4.2.1:53
	nameserver dns-1  8.8.8.8:53
	nameserver dns-2  4.4.2.2:53
	nameserver dns-3  8.8.4.4:53
	hold valid 300s

backend infra-ddns
	mode http
        timeout connect 60s
	timeout server  60s
	server ddns1 ddns.domain.net:9000 resolvers dns check
	server ddns2 ddns2.domain.net:9000 resolvers dns check 
```

**Comment by viict** [comment]
@vfarcic that is great! only one caveat is that not all the services need to use the resolver, is there an way to set this by service?

Because I belive that as of now when the CHECK_RESOLVERS is True all the services will have this applied, right?

**Comment by vfarcic** [comment]
Done!

There's a new env. var. `RESOLVERS` (described in [Environment Variables](http://proxy.dockerflow.com/config/#environment-variables) section of the documentation.

**Comment by vfarcic** [comment]
I can add a parameter that would overwrite env. var. `CHECK_RESOLVERS`. Can you open a new issue?
