### ISSUE TITLE
Redirecting to external domain with dockere-flow-proxy

### ISSUE THREAD

**Issue by aleskinen** [docker-flow/docker-flow-proxy#102]
**Description**

**Comment by vfarcic** [comment]
Is there any particular reason for that? Normally, internal k8s proxy is used only for internal applications and the external LB should handle redirections to one cluster or another.

**Comment by aleskinen** [comment]
We have need for about 30 redirections currently done with external machine I want to retire. Since HAproxy is capable for doing this, I thought it would be nice not to need external computer for that. 

On swarm http ports are already taken so I can not use one container in swarm machines to do that. 

And if I put nginx container behind dfp for redirections, when it receives the traffic address is service address, not the original. So I can not anymore do redirections there.

One easy option would be to include static config file to haproxy config where redirections are defined. Then actual operation fo dfp would need not change. But for that I would need to modify dfp image.

**Comment by vfarcic** [comment]
That should be a minor change to the project. However, I'm afraid that the best chance of having that done would be for you to make a pull request. Almost everyone (me included) moved to Kubernetes and this project is, more or less, abandoned. I think there was only one release in the last six months or more.

**Comment by lleox** [comment]
Hi @aleskinen 

If this issue is still relevant, please feel free to open an issue in the fork I created.

https://github.com/freedomwatchers/docker-flow-proxy/issues/new

**Comment by lleox** [comment]
Dear @aleskinen 

If this issue is still relevant, please feel free to leave a comment here.

**Comment by aleskinen** [comment]
I have moved to kube, thanks.
