### ISSUE TITLE
HAProxy configuration errors

### ISSUE THREAD

**Issue by goncalo-oliveira** [docker-flow/docker-flow-proxy#103]
Hi guys,

I started having issues today with my proxy, after being working in a healthy way for more than 6 months. I've already tried to restart the proxy but I keep getting errors in the configuration.

[ALERT] 255/125422 (30) : parsing [/cfg/haproxy.cfg:51] : 'bind *:443' : 'crt-list' : error processing line 1 in file '/cfg/crt-list.txt' : unable to load SSL private key from PEM file '/certs/grafana.fonixcloud.com.pem'.

Can anyone point me in the right direction?

Docker version

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Proxy version: 19.08.11-18

**Comment by goncalo-oliveira** [comment]
The certificates on the certs folder were for some reason. I wonder why this got corrupted. I copied some of the certificates here, and got further ahead on the process, but now, some of the certificates are missing, from both certs and letsencrypt folder.

I wonder how this came to be, and more importantly, how can I solve this, how can I somehow "reset" some certificates?

**Comment by vfarcic** [comment]
Certs are probably stored in a network drive and my best guess is that there's something wrong going on there.

**Comment by goncalo-oliveira** [comment]
Well, that's what I though initially, but it doesn't seem like it. The certificates are in a network drive yes, but I've double check permissions and all and it looks good. What's weird is the change in behaviour, as it's running for some time and certificates were already created and renewed.
Either way, I'm closing the issue, as this has nothing to do with the proxy, but with the letsencrypt component, most likely. I'm using a fork from https://github.com/n1b0r/docker-flow-proxy-letsencrypt.
