### ISSUE TITLE
Docker Flow Proxy will not start

### ISSUE THREAD

**Issue by christianmscott** [docker-flow/docker-flow-proxy#104]
**Description**

When creating a barebones, example instance of docker flow proxy with swam-listener, per the instructions with docker-ce 19.03.5 on Ubuntu Server 18.04.3, swarm listener starts fine, but docker flow proxy does not. It seems it cannot bind to 443 and 80 with the overlay network. Error message is:

failed to activate service binding for container proxy_proxy.1.sv5vggn7fl9adgamt0jrl1thd after healthy event" error="network sandbox does not exist for container proxy_proxy.1.sv5vggn7fl9adgamt0jrl1thd

**Steps to reproduce the issue:**
1. Create overlay network proxy - docker network create --driver overlay proxy
2. Create proxy stack based on the following example configuration:

version: "3"

services:

  proxy:
    image: dockerflow/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true

3. Done - the swarm listener service starts successfully, proxy does not and keeps retrying. 

**Describe the results you received:**

Docker flow proxy does not start. 

**Describe the results you expected:**

Docker flow proxy should start

**Additional information you deem important (e.g. issue happens only occasionally):**

This has happened on every fresh installation of ubuntu server/docker-ce I have tried. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hyper-V Virtual Machine.

**Comment by vfarcic** [comment]
My laptop is currently in Apple shop (replacing keyboard). I'll check it out in a few days (once it's back).

**Comment by vfarcic** [comment]
I tried and failed to reproduce the issue. It's probably related to networking on the cluster itself. Can you double-check that you can connect other services through Overlay network?

P.S. This project is (mostly) abandoned. There haven't been new releases for a while now. Most of the people moved away from Docker Swarm.

**Comment by lleox** [comment]
Hi @christianmscott 

Please feel free to copy this issue in the fork I created.

https://github.com/freedomwatchers/docker-flow-proxy/issues/new

**Comment by lleox** [comment]
Closed due to inactivity
