### ISSUE TITLE
Disable old versions of TLS and SSL

### ISSUE THREAD

**Issue by mwillema** [docker-flow/docker-flow-proxy#105]
Hi everyone,

Is there an easy way to disable the old versions of TLS and SSL in the configuration?

Best regards,
Marco

**Comment by lleox** [comment]
Hi @mwillema 

If this issue is still relevant, please feel free to open an issue in the fork I created.

https://github.com/freedomwatchers/docker-flow-proxy/issues/new

**Comment by lleox** [comment]
Closed by inactivity.
Feel free to create a new issue if required.
