### ISSUE TITLE
Adding security headers

### ISSUE THREAD

**Issue by mwillema** [docker-flow/docker-flow-proxy#106]
Hi everyone,

Is there a way to easily add the following headers to the responses through the reverse proxy?

- HTTP Strict-Transport-Security
- X-XSS-Protection
- X-Content-Type-Options

Thanks!

**Comment by vfarcic** [comment]
Unfortunately, there hasn't been any changes to the project for a while now. All contributors, including me, switched to Kubernetes.

**Comment by lleox** [comment]
Dear @mwillema 

If this issue is still relevant, please feel free to leave a comment here.

**Comment by lle0x** [comment]
Closed due to inactivity
