### ISSUE TITLE
Feature: Validate signed JWT tokens

### ISSUE THREAD

**Issue by dazinator** [docker-flow/docker-flow-proxy#108]
I was looking around for a proxy that could authenticate requests by ensuring there was a valid signed JWT token in the Authorization: Bearer header.

According to this:  https://www.haproxy.com/blog/using-haproxy-as-an-api-gateway-part-2-authentication/ HAProxy can do this using LUA scripting and some variables like the public key. JWT tokens would be generated using asymmetric cryptography so only the public key is required to verify the signature.

Do you think this would be a feature worth tackling? Or perhaps it's already achievable?

**Comment by lleox** [comment]
Dear @dazinator 

If this issue is still relevant, please feel free to leave a comment here.

**Comment by lle0x** [comment]
Closed due to inactivity

**Comment by dazinator** [comment]
Just an update to say I might circle back to this but at the moment I'm exploring traefik to see if that can do something similar.
