### ISSUE TITLE
how to whitelist a specific path

### ISSUE THREAD

**Issue by cosmos1978** [docker-flow/docker-flow-proxy#109]
I have a service running with the following config

deploy:
  labels:
   - com.df.notify=true
   - com.df.serviceDomain=kibana.elkprod.idtv.bc
   - com.df.port=5601
I would only like to allow request to this path /s/eng/app/dashboards all the rest should be blocked.

Can someone assist me in this I assume trivial request. ?

It should be all paths starting with /s/eng/app/dashboards
so for example domain.example/s/eng/app/dashboards/bla/bla?test should also work

**Comment by lleox** [comment]
Dear @cosmos1978  

If this issue is still relevant, please feel free to leave a comment here.

**Comment by lle0x** [comment]
Closed due to inactivity
