### ISSUE TITLE
Documentation URL (dockerflow.com) is for sale

### ISSUE THREAD

**Issue by rendragnet** [docker-flow/docker-flow-proxy#112]
Hi Team,

The documentation link in the readme goes to http://proxy.dockerflow.com/ - however this redirects to hugedomains.com and asks if you'd like to buy the domain..  Might need to update with where the documentation is now hosted?

Thanks,

DG

**Comment by lleox** [comment]
Main and development branches were updated to internal documentation.

I created a [new issue](https://github.com/docker-flow/docker-flow-proxy/issues/113) to publish documentation through Github Pages.
