### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by ruudboon** [docker-flow/docker-flow-proxy#14]
By default docker-flow-proxy isn't listening only to ipv4 could we have an option to listen to ipv6 also?

```
root@f22d1f4a9ec5:/# netstat -anp | grep :80
tcp        0      0 172.x.x.x:44546        123.123.123.123:80        TIME_WAIT   -               
tcp        0      0 172.x.x.x:34684        123.123.123.123:80        TIME_WAIT   -               
tcp        0      0 172.x.x.x:37834        123.123.123.123:80         TIME_WAIT   - 
```

**Comment by BretFisher** [comment]
AFAIK Docker Overlay networks only support IPv4

**Comment by vfarcic** [comment]
Thanks @BretFisher.

@ruudboon I somehow lost track of this issue. As @BretFisher said, making the proxy support IPv6 would not help since Overlay is still IPv4.

**Comment by ruudboon** [comment]
Are you sure ipv6 isn’t supported on overlay?

Thing like this are working
‘’’
version: '2.1'

networks:
  app_net:
    enable_ipv6: true
    driver: overlay
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
      -
        subnet: 2001:3984:3989::/64
‘’’

**Comment by BretFisher** [comment]
It would be great if you could reference a PR or issue where it works...
every moby/moby and libnetwork and swarmkit issue related to ipv6 overlay
ends in "not supported on overlay driver" from what I see.
