### ISSUE TITLE
Update haproxy version

### ISSUE THREAD

**Issue by fpga-tom** [docker-flow/docker-flow-proxy#15]
**Description**

Would it be possible to update haproxy 1.8.3 to newer version?

When using IE in win10 with https (haproxy is ssl termination), it uses http/2 by default. As result some pages don't load because it takes to long and there is timeout. In chrome and firefox this works.
I tried to building custom image with haproxy 1.8.4 and it resolved the issue. So would it be possible to
update version in Dockerfile?

**Comment by vfarcic** [comment]
`dockerflow/docker-flow-proxy:18.05.05-43` uses HAProxy 1.8.8. Can you please try it out and let me know if you notice any problem?

**Comment by fpga-tom** [comment]
It works fine. Thank you.
