### ISSUE TITLE
[feature request] Ability to overwrite CHECK_RESOLVERS per service

### ISSUE THREAD

**Issue by viict** [docker-flow/docker-flow-proxy#2]
**Description**

The issue #1 introduced the RESOLVERS enviroment but it rely on the CHECK_RESOLVERS enviroment and right now we can't overwrite it on a per service basis.

**Describe the results you expected:**

Be able to set CHECK_RESOLVERS per service

**Comment by vfarcic** [comment]
It finished and available as `dockerflow/docker-flow-proxy:18.04.10-22`. Release notes are in [18.04.10-22](https://github.com/docker-flow/docker-flow-proxy/releases/tag/18.04.10-22).
