### ISSUE TITLE
DFP reloads config every second on each instances

### ISSUE THREAD

**Issue by netadvanced** [docker-flow/docker-flow-proxy#31]
**Description**
I'm experiencing random 503 errors and I was wondering if two things could be linked ?!  
Could it be some latency induced by the reloading of the config ?
I have 3 instances running and all of them spit out logs by the second, reloading and validating the configuration

**Describe the results you received:**
proxy_proxy.3.cex3u74s4xfh@mgr3    | 2018/06/29 06:32:52 Reloading the proxy
proxy_proxy.3.cex3u74s4xfh@mgr3    | 2018/06/29 06:32:52 Validating configuration
proxy_proxy.3.cex3u74s4xfh@mgr3    | Configuration file is valid
proxy_proxy.3.cex3u74s4xfh@mgr3    | 2018/06/29 06:32:52 Proxy config was reloaded
proxy_proxy.3.cex3u74s4xfh@mgr3    | 2018/06/29 06:32:57 Reloading the proxy
proxy_proxy.3.cex3u74s4xfh@mgr3    | 2018/06/29 06:32:57 Validating configuration
proxy_proxy.3.cex3u74s4xfh@mgr3    | Configuration file is valid
proxy_proxy.3.cex3u74s4xfh@mgr3    | 2018/06/29 06:32:58 Proxy config was reloaded
proxy_proxy.3.cex3u74s4xfh@mgr3    | 2018/06/29 06:33:03 Reloading the proxy
proxy_proxy.3.cex3u74s4xfh@mgr3    | 2018/06/29 06:33:03 Validating configuration
proxy_proxy.3.cex3u74s4xfh@mgr3    | Configuration file is valid
proxy_proxy.3.cex3u74s4xfh@mgr3    | 2018/06/29 06:33:03 Proxy config was reloaded
proxy_proxy.1.i54r1xgen9nd@node3    | 2018/06/29 06:33:04 Reloading the proxy
proxy_proxy.1.i54r1xgen9nd@node3    | 2018/06/29 06:33:04 Validating configuration
proxy_proxy.1.i54r1xgen9nd@node3    | Configuration file is valid
proxy_proxy.1.i54r1xgen9nd@node3    | 2018/06/29 06:33:04 Proxy config was reloaded
proxy_proxy.2.osq32xxyjhij@node1    | 2018/06/29 06:33:07 Reloading the proxy
proxy_proxy.2.osq32xxyjhij@node1    | 2018/06/29 06:33:07 Validating configuration
proxy_proxy.2.osq32xxyjhij@node1    | Configuration file is valid
proxy_proxy.2.osq32xxyjhij@node1    | 2018/06/29 06:33:07 Proxy config was reloaded

**Additional information**
DFP version :latest
Docker version 18.03.1-ce

***DFP Swarm config***
version: "3.2"
networks:
  proxy:
    external: true
services:
  proxy:
    image: dockerflow/docker-flow-proxy:${DFPTAG:-latest}
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - CONNECTION_MODE=${CONNECTION_MODE:-http-keep-alive}
    deploy:
      replicas: 3
  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:${DFPSLTAG:-latest}
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

**Services configuration**
-- extract:

    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=host.domain.com
        - com.df.port=8069
        - com.df.reqMode=http

**Comment by thomasjpfan** [comment]
This is mostly caused by the HEALTHCHECK I introduced in the last commit. I'm looking into it.

**Comment by thomasjpfan** [comment]
I fixed this bug in `dockerflow/docker-flow-proxy:18.06.29-65`.

**Comment by thomasjpfan** [comment]
I reintroduced the HEALTHCHECK without this bug. Please test it out at `dockerflow/docker-flow-proxy:18.06.29-66`.

**Comment by netadvanced** [comment]
Thanks very much thomasjpfan
I'll go to the office and test it today. Will post feedback.
Cheers

**Comment by netadvanced** [comment]
Thanks very much @thomasjpfan, it all works as designed now !!  
Cheers, big thanks for the prompt fix, really appreciated !!
