### ISSUE TITLE
Docker Swarm + SSL = SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by patrick-motard** [docker-flow/docker-flow-proxy#38]
**Steps to reproduce the issue:**

Following the instructions found [here](https://proxy.dockerflow.com/certs/).

I used certbot to generate a certificate for my subdomain using docker on the masternode:

```
sudo docker run --rm \
-p 81:81 -p 443:443 -p 80:80 \
-v /etc/letsencrypt:/etc/letsencrypt \
certbot/certbot certonly \
-d my-subdomain.mydomain.com \
--standalone \
-m myemail@mydomain.com --agree-tos
```

Which resulted in:

```
./cert
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for my-subdomain.my-domain.com
Waiting for verification...
Cleaning up challenges
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/my-subdomain.my-domain.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/my-subdomain.my-domain.com/privkey.pem
   Your cert will expire on 2018-10-09. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```

Then i added the pem to the df-proxy service:

```
docker secret create cert-my-subdomain.mydomain.com /etc/letsencrypt/live/my-subdomain.mydomain.com/fullchain.pem
docker service update --secret-add cert-my-subdomain.mydomain.com proxy_proxy
```

**Describe the results you received:**

`https://my-subdomain.my-domain/demo/hello` results in -> 

```
Secure Connection Failed

An error occurred during a connection to menards-test.wts-ops.com. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG 
```

`http://my-subdomain.my-domain/demo/hello` results in ->

```
503 Service Unavailable
No server is available to handle this request. 
```

**Describe the results you expected:**

http redirects to https, and https resolves with "hello world" in browser. 

**Additional information you deem important (e.g. issue happens only occasionally):**

Before adding the secret to the proxy service, hello world was resolving on http. It no longer does after adding secret. Odd.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker Swarm. Azure. Deployed proxy and hello demo using "[swarm mode with docker stack tutorial](https://proxy.dockerflow.com/swarm-mode-stack/)

**Comment by thomasjpfan** [comment]
HAProxy expects the combination of `fullchain.pem` and `privkey.pem`. You can do this by running:

```bash
export DOMAIN=my-subdomain.mydomain.com

# Combine files
cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem \
/etc/letsencrypt/live/$DOMAIN/privkey.pem > ~/$DOMAIN.pem

# create docker secret
docker secret create cert-$DOMAIN.pem ~/$DOMAIN.pem
```

**Comment by patrick-motard** [comment]
@thomasjpfan thank you!! That fixed the issue for me. I'm going to create a PR to add information about using LetsEncrypt to the documentation of this project.

On a side note.. you wouldn't happen to be able to know if this project supports multiple certs/subdomains would you?

**Comment by thomasjpfan** [comment]
DFP does support multiple certs. You can add them by creating a `cert-$DOMAIN.pem` for each domain you want to support.

**Comment by patrick-motard** [comment]
@thomasjpfan Okay thank you for that information. I'll include that in my write-up.
