### ISSUE TITLE
DFP causes too many redirects on clients.

### ISSUE THREAD

**Issue by alshabib** [docker-flow/docker-flow-proxy#4]
**Description**

When using DFP to redirect http requests to https, the client accessing the url quits reporting too many redirects.
 
**Steps to reproduce the issue:**
1. Create proxy network
2. Create cert secret
3. Deploy [proxy-stack.yml](https://github.com/docker-flow/docker-flow-proxy/files/1913345/proxy-stack.yml.txt) and [go-demo.yml](https://github.com/docker-flow/docker-flow-proxy/files/1913344/go-demo.yml.txt)
4. curl -L https://test.mydomain.com/demo/hello (you may need to change domain)

**Describe the results you received:**

```curl: (47) Maximum (50) redirects followed```

**Describe the results you expected:**

``` Hello, World!```

**Additional information you deem important (e.g. issue happens only occasionally):**

Previous versions of DFP did not have this problem (in particular, vfarcic/docker-flow-proxy:17.10.22-47). 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

[DFP logs](https://github.com/docker-flow/docker-flow-proxy/files/1913349/logs.txt) when the go-demo service is deployed. Here is a [trace](https://github.com/docker-flow/docker-flow-proxy/files/1913354/trace.txt)

Tried on AWS and Virtualbox environment.

**Comment by vfarcic** [comment]
The patch should probably be applied to https://github.com/docker-flow/docker-flow-proxy/blob/master/proxy/template.go . Please let me know if you'll give it a try with a PR.

**Comment by vfarcic** [comment]
It's available starting from `dockerflow/docker-flow-proxy:18.04.16-36`.

**Comment by alshabib** [comment]
Great thanks!
