### ISSUE TITLE
http check support

### ISSUE THREAD

**Issue by remy-tiitre** [docker-flow/docker-flow-proxy#42]
I think I could add this myself with custom template support but maybe this is something that most of the users would need they just don't know it.

HAProxy has health check support, and in case of containerized environment thats something we really want. We do not want to sent trafic to instances that are still starting up or shutting down.

More information from here: https://www.serverlab.ca/tutorials/linux/network-services/how-to-configure-haproxy-health-checks/

**Comment by vfarcic** [comment]
DFP does not send traffic to individual replicas of a service. It sends it to the service DNS and let's Docker's Overlay network do round robin. If applications in containers are following best practices (SIGTERM signals, health checks, and so on), the whole deal works pretty well and better than if HAProxy takes care of it.

**Comment by remy-tiitre** [comment]
In tcp level, yes. But if I want to set up http checks then no. Thats why kubernetes has also two different types of probes. In most simplistic terms, the fact that my tomcat is up does not mean that my application is ready to take requests.
