### ISSUE TITLE
Map one service with multiple ports to multiple addresses

### ISSUE THREAD

**Issue by no-more** [docker-flow/docker-flow-proxy#43]
**Description**
I don't know if it's a bug or a feature. I have a service api that have multiple listening ports. Let's say one for public and one for admin/private. I want to publish each port to a different serviceDomain.
**[I'm using manual configuration (with curl call).]**
Each configuration works well, but I didn't manage to make them work together. The last one always override the previous configuration for the same serviceName. I suspect a name matching is done before inserting a new service but it does not take port in consideration.
I would like **serviceA:8080 -> public.test.com** and **serviceA:8090 -> admin.test.com**

**Steps to reproduce the issue:**
1. Create multi port container
2. **Using manual config** map each port to a different domainName

**Describe the results you received:**
Last config override the previous one for a same serviceName

**Describe the results you expected:**
Each port should be accessible on the requested domaineName

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

BTW thanks a lot for this great product.

**Comment by thomasjpfan** [comment]
Can you post your `stack` file or docker commands you use to setup your service?

**Comment by no-more** [comment]
I'm creating the service like this : 
```
docker service create \
                            --name proxy \
                            --detach=true \
                            -p 80:80 \
                            -p 443:443 \
                            -p 8080:8080 \
                            --network "frontend" \
                            -e MODE=swarm \
                            --env DEBUG=true \
                            "dockerflow/docker-flow-proxy:18.07.18-74";
```

then I load the proxy config with curl command : 
```http://mydomain:8080/v1/docker-flow-proxy/reconfigure?serviceName=test-stockmovement-server&servicePath=/&serviceDomain=test-stockmovement-server.dev.mydomain&port=3000```
and for the second port : 
```http://mydevserver:8080/v1/docker-flow-proxy/reconfigure?serviceName=test-stockmovement-server&servicePath=/&serviceDomain=test-stockMovement-server-backend.dev.mydomain&port=3001```

As explained before, everything works individualy, but not together. Only the last called command is active (for the same serviceName `test-stockmovement-server`)

Is that what you asked for ? 

Thanks for your help.

**Comment by thomasjpfan** [comment]
To configure DFP to direct traffic based on `serviceDomain` try the following:

```
curl "http://mydomain:8080/v1/docker-flow-proxy/reconfigure?\
serviceName=test-stockmovement-server&\
servicePath.1=/&serviceDomain.1=test-stockmovement-server.dev.mydomain&port.1=3000&\
servicePath.2=/&serviceDomain.2=test-stockMovement-server-backend.dev.mydomain&port.2=3001"
```

The indexes allow you have multiple destinations for a single service. You can further restrict the port by adding `srcPort.{1,2}=80` by calling:

```
curl "http://mydomain:8080/v1/docker-flow-proxy/reconfigure?\
serviceName=test-stockmovement-server&\
servicePath.1=/&srcPort.1=80&serviceDomain.1=test-stockmovement-server.dev.mydomain&port.1=3000&\
servicePath.2=/&srcPort.2=80&serviceDomain.2=test-stockMovement-server-backend.dev.mydomain&port.2=3001"
```

This way only http requests on port 80 will be directed to your services. You can learn about other parameters in the [Usage docs](http://proxy.dockerflow.com/usage/).

**Comment by no-more** [comment]
Thank you very much that's exactly what I needed!
