### ISSUE TITLE
PathType cannot be suffixed with an Index.

### ISSUE THREAD

**Issue by darkl0rd** [docker-flow/docker-flow-proxy#45]
I have a backend which listens on two ports, 8000 and 8008. On port 8000 the service talks "http", on 8008 and it speaks an arbitrary protocol, on top of that it will only accept traffic when a given SNI header is provided.

As such,  to route my traffic I need to use a mixtures of request modes, namely http and sni. This works well using the index suffix you can provide to reqMode. However, one cannot currently do the same for pathType meaning that the config will either be using a) path_beg (the default) for both or b) whatever I put in com.df.pathType.

Can we please allow for pathType to also support an index suffix?

The outcome I would like to see is that I can render the following configuration:

```
frontend services
    bind *:80
    bind *:443 ssl crt-list /cfg/crt-list.txt alpn h2,http/1.1
    mode **http**
    option  forwardfor 
    ...
    acl url_xxx8000_1 **path_beg** /path
    acl domain_xxx8000_1 hdr_beg(host) -i myhost.mydomain
   
frontend service_443
    bind *:443
    mode **tcp**
    tcp-request inspect-delay 5s
    tcp-request content accept if { req_ssl_hello_type 1 }
    acl sni_xxx8008_2 **req_ssl_sni -m reg -i** MyMagicSNIHeader
    ....

**Comment by thomasjpfan** [comment]
Can you provide the stack file or docker commands you are thinking of using to create that haproxy configuration?

**Comment by darkl0rd** [comment]
Absolutely, applying the labels below should result in such a config if com.df.pathType.2 would be respected.

--- 
  deploy:
    labels:
        - com.df.notify=true
        - com.df.distribute=true

        - com.df.serviceDomain.1=myhost.mydomain
        - com.df.servicePath.1=/path
        - com.df.srcPort.1=443
        - com.df.port.1=8000
        - com.df.reqMode.1=http

        - com.df.pathType.2="req_ssl_sni -i"
        - com.df.servicePath.2=MyMagicSNIHeader
        - com.df.srcPort.2=443
        - com.df.port.2=8008
        - com.df.reqMode.2=sni

**Comment by thomasjpfan** [comment]
I added this feature in `dockerflow/docker-flow-proxy:18.08.01-76`. Please test it out and see if it works for your use case.

**Comment by darkl0rd** [comment]
Hi Thomas, I have just tested your addition and it works as expected.

What I didn't realize before is that defining the frontends like in my initial post, that is having the same port twice with different protocols would result in RR style request handling.

So even though this is definitely a step in the right direction, I'm not quite there yet :) With your addition though, I can now create a customized template which contains one static block to split out the traffic.

**Comment by thomasjpfan** [comment]
What HAProxy configuration are you thinking of using to address your issue?

**Comment by darkl0rd** [comment]
An example (generated through docker-gen, and obfuscated with fake names):

frontend ssl 
    bind *:443 ssl crt-list /etc/haproxy/crt-list.txt # Terminate SSL.
    mode tcp
    option tcplog
    acl is_http ssl_fc_sni -i my.tomcat.fqdn
    acl my_magic_sni_1 -i my_magic_sni_1
    acl my_magic_sni_2 -i my_magic_sni_2

    use_backend http if is_http
    use_backend my_magic_sni1 if my_magic_sni1
    use_backend my_magic_sni2 if my_magic_sni2

    default_backend http

backend http # Deal with HTTP traffic to my.tomcat.fqdn
    mode tcp
    option tcplog
    server http 127.0.0.1:1445

frontend http # Deal with HTTP traffic sent to my.tomcat.fqdn, and do path based routing.
    bind *:1445 alpn h2,http/1.1
    mode http
    option httplog
    option dontlognull
    option contstats
    option forwardfor

    use_backend http_my_tomcat_fqdn_1 if { path_beg /my_path_1 }
    use_backend http_my_tomcat_fqdn_2 if { path_beg /my_path_2 }
          
backend http_my_tomcat_fqdn_1
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server http_my_tomcat_fqdn_1 1.2.3.4:8080

backend my_magic_sni_1
   mode tcp
   server my_magic_sni_1 1.2.3.4:8088

**Comment by thomasjpfan** [comment]
Ah I see. Thank you for the information!
