### ISSUE TITLE
customize error pages

### ISSUE THREAD

**Issue by davidwmartines** [docker-flow/docker-flow-proxy#48]
Can you please add more details on how to use custom error pages.  Preferably the solution is not to create a custom image.  I would like the error pages to be stored on the file system outside of docker for easy maintenance (actually a mounted share to be used across the swarm).   Can I use a  bind mount to `/errorpages`?   That did not work for me, I guess because image does not expose it.

**Comment by thomasjpfan** [comment]
Can you post the docker-compose file or docker CLI commands you use when attempting to create custom error pages?

**Comment by vfarcic** [comment]
Closing as inactive
