### ISSUE TITLE
Feature request: Default certificate if no SNI is present (for WinXP clients)

### ISSUE THREAD

**Issue by Vinno97** [docker-flow/docker-flow-proxy#52]
**Feature request**
A way to specify what certificate Docker Flow whould use when there is no SNI field present in the TLS handshake. 

**Context**
Hi, I have a setup where one server can be reached reached from root of the domain and one via a subdomain. It all seems to work, untill I try to reach reach the main domain from a WinXP client using IE8. IE on XP does not have support for SNI, which caused HAProxy to default to the first certificate it has, which is based on their alphabetical order in the `certs` directory. I do not have control over how the certificates are named, since I use [docker-flow-letsencrypt](https://github.com/hamburml/docker-flow-letsencrypt) which names them after the domain that they belong to.

```sh
/ # ls certs
portainer.domain.nl.combined.pem  domain.nl.combined.pem
```

**Current workaround**
Luckily my main domain name starts with a **b** and the first subdomain starts with a **p**, this issue only occurs on my dev server on a different domain. On the dev server its possible to change the subdomain from subdomain.domain.nl to zsubdomain.domain.nl

**Comment by thomasjpfan** [comment]
The order of the certificates depends on the order of the certs in `/cfg/crt-list.txt`. One way to address your issue is to add an ENV variable: `PREFERRED_CRTS_STARTS_WITH=portainer.domain.nl,bob.domain.nl`. This will force certs that starts with `portainer.domain.nl` to come first, than `bob.domain.nl` next. The rest of the crts will below these preferred crts.

What do you think?

**Comment by Vinno97** [comment]
That seems like quite an elegant solution.

The name `PREFERRED_CRTS_STARTS_WITH`, however,  does not feel very intuitive to me. It is descriptive when you know what it actually does, but I expect I would have to google its function if I would see it defined in a random `docker-compose` file that I did not write.

Something like `DEFAULT_CERTIFICATE` or `PREFERRED_CERTIFICATE` could be more easy to understand, though, though they're not as descriptive if the values are matched on the beginning of the certificate names. This brings me to another idea: perhaps also make it match by globbing or regex? Then it could be something like `PREFERRED_CERTIFICATE=portainer.domain.nl*, bob.*`. 

Any input?

**Comment by thomasjpfan** [comment]
I like the `PREFERRED_CERTIFICATE` name and the globing idea.

**Comment by thomasjpfan** [comment]
This feature has been added to `dockerflow/docker-flow-proxy:18.08.22-84`. Please test it out and see if it works for your use case.

**Comment by Vinno97** [comment]
Thank you Thomas, it works beautifully
