### ISSUE TITLE
sessionType=sticky-server does not reload on service container change

### ISSUE THREAD

**Issue by paulrobello** [docker-flow/docker-flow-proxy#56]
I have a web server service running 2 instances of a web application.
When i do a rolling update of my service or scale it up or down the proxy is not getting notified causing the proxy to not be able service requests for that service.

[docker-compose.txt](https://github.com/docker-flow/docker-flow-proxy/files/2337370/docker-compose.txt)

**Comment by thomasjpfan** [comment]
The older vfarcic prefixed images has not been updated in a while. Can you update to `dockerflow/docker-flow-proxy` and `dockerflow/docker-flow-swarm-listener` and see if your issue still persist?

**Comment by paulrobello** [comment]
That did the trick. Thank you sir.
