### ISSUE TITLE
multiple services mapped under a common name

### ISSUE THREAD

**Issue by cazacugmihai** [docker-flow/docker-flow-proxy#6]
Because the project has a new location, I'm transferring the [issue](https://github.com/vfarcic/docker-flow-proxy/issues/434) here.

Hi,

Let's say that we have three services and each one is listening on port 8888 but it is started with a different configuration (e.g. a different mounting volume).

Is there a way to configure the proxy in order to obtain this behavior:
when we are trying to access http://localhost/, the proxy will redirect the request to any service that is alive?

Thank you!

**Comment by vfarcic** [comment]
@cazacugmihai The solution from #11 should work for your use case as well. Can you please confirm?

**Comment by cazacugmihai** [comment]
It's perfect! Thank you!
