### ISSUE TITLE
Logging configuration

### ISSUE THREAD

**Issue by remy-tiitre** [docker-flow/docker-flow-proxy#73]
When I want to use HAProxys native syslog logging facility how should I configure it in docker-flow-proxy. Use templates? Frontend and Global extra blocks? I understand that from syslog perspective I either have to use remote IP or map /dev/log from host into container.

**Comment by thomasjpfan** [comment]
From my understanding `docker-flow-proxy` already watches the syslogs from haproxy, what issue are you running into when trying to use HAProxys native syslog?

**Comment by remy-tiitre** [comment]
I want it to log directly to my syslog server and not to a console. It has been correctly noted that DEBUG=true should not be used in production. I don't need logs for debugging purposes but for auditing purposes. It would be foolish to redirect HAProxy logs to docker console and then use docker syslog logging driver.

**Comment by remy-tiitre** [comment]
Well, best place is probably HAProxy manual. But it's not that complicated. What I would add is:

**Comment by thomasjpfan** [comment]
DFP supports adding additional config options by setting `EXTRA_GLOBAL=log host.docker.internal:514 local0` and `EXTRA_FRONTEND=log global,option httplog,option dontlognull`.

**Comment by remy-tiitre** [comment]
Can be closed. That was my original question if this should be done with EXTRA_* variables.
