### ISSUE TITLE
Configure Load Balancer Instance Protocol

### ISSUE THREAD

**Issue by jboettcher1** [docker-flow/docker-flow-proxy#79]
**Description**
Maybe this isn't an issue but I have posted on a number of forums regarding this and have not gotten any help. I am unable to configure my load balancer's instance protocol via labels. Everytime I update my DFP my load balancer's instance protocol gets set/reset to TCP (I want it to be SSL). Setting the LB's protocol that it listens on is straight forward but setting the protocol to be used when sending traffic to instances is not, at least as far as I have found. Any help would be appreciated!

**My Proxy Compose:**
  proxy:
    image: ${STACK_IMAGE_TAG}
    ports:
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2
      labels:
        - "com.docker.aws.lb.arn=${ACM_CERTIFICATE_ARN}"

**Describe the results you received:**
Load Balancer Protocol     Load Balancer Port      Instance Protocol     Instance Port     Cipher     SSL Certificate
SSL                        443	                   TCP	                 443	           Change	  ******************* (ACM) Change

**Describe the results you expected:**
Load Balancer Protocol     Load Balancer Port      Instance Protocol     Instance Port     Cipher     SSL Certificate
SSL                        443	                   SSL	                 443	           Change	  ******************* (ACM) Change

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS Classic Load Balancer

**Comment by vfarcic** [comment]
This project needs adoption. I moved to Kubernetes and cannot dedicate time to this project anymore. Similarly, involvement from other contributors dropped as well. Please consider contributing yourself if you think this project is useful.

**Comment by lleox** [comment]
Dear @jboettcher1 

If this issue is still relevant, please feel free to leave a comment here.

**Comment by lle0x** [comment]
Closed due to inactivity
