### ISSUE TITLE
Feature: Add multiple configuration lines with 'BackendExtra'

### ISSUE THREAD

**Issue by aisbergg** [docker-flow/docker-flow-proxy#85]
It would be nice to add multiple lines to the backend with `BackendExtra`. Like other parameters the string should be separated with a comma.

**Comment by thomasjpfan** [comment]
Currently, `BackendExtra` does not support the comma to new-line notation. This may be because there are some haproxy options that use comma, such as `resolve-opts`: https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.2-resolve-opts

**Comment by dimovnike** [comment]
This would be definitely great to have. I also need this option.

**Comment by chrsch** [comment]
I also would love to see this.

**Comment by thomasjpfan** [comment]
My only concern with adding this feature using comma as a separator is that it will break backwards compatibility. For example:

```
http-request set-header x-path %[hdr(x-path),regsub(/+,/,g)]
```

In this case, the comma needs to be there.

**Comment by chrsch** [comment]
I see. Two quick options then came to my mind earlier this day:
- Take an other delimiter (;; && ...) and implement a Split function (like described here: https://stackoverflow.com/questions/19771787/golang-how-to-split-string-in-template)
- Make an extra option BackendExtraMultiline which needs "," escaped if not used as a line delimiter

**Comment by thomasjpfan** [comment]
We could give the user complete control by adding `BackendExtraMultilineSeparator`.

**Comment by chrsch** [comment]
Oh yes I like this idea.

**Comment by vfarcic** [comment]
This project needs adoption. I moved to Kubernetes and cannot dedicate time to this project anymore. Similarly, involvement from other contributors dropped as well. Please consider contributing yourself if you think this project is useful.

**Comment by lleox** [comment]
Dear @aisbergg 

If this issue is still relevant, please feel free to leave a comment here.

**Comment by aisbergg** [comment]
I moved to [Traefik](https://github.com/traefik/traefik)
