### ISSUE TITLE
Feature: Authentication for reconfiguration requests

### ISSUE THREAD

**Issue by aisbergg** [docker-flow/docker-flow-proxy#86]
From a security perspective it would be great if the reconfiguration requests on port 8080 can be restricted via authentication or via specification of trustworthy swarm listener IPs. For starters, a simple secret passed along with a reconfiguration request would do the trick. The thing is, I want to able to stop a rogue container from reconfiguring my reverse proxy and taking over my network.

**Comment by vfarcic** [comment]
This project needs adoption. I moved to Kubernetes and cannot dedicate time to this project anymore. Similarly, involvement from other contributors dropped as well. Please consider contributing yourself if you think this project is useful.

**Comment by lleox** [comment]
Dear @aisbergg 

If this issue is still relevant, please feel free to leave a comment here.
