### ISSUE TITLE
IP address exhaustion

### ISSUE THREAD

**Issue by jwalkins2017** [docker-flow/docker-flow-proxy#88]
**Description**

I am replicating multiple test environments behind a single DFP instance and have hit an IP exhaustion issue with all the containers being on the same "proxy" network. Is it possible to partition out the networks or have multiple DFP for each environment on the same swarm?

**Steps to reproduce the issue:**
1. Have more that 200 containers behind the DFP

**Describe the results you received:**
Containers are stuck in the new task.

**Describe the results you expected:**
Containers should start up normally.

**Additional information you deem important (e.g. issue happens only occasionally):**
Once I removed an environment, I was able to start up other containers.

**Comment by vfarcic** [comment]
That sounds like a problem with Swarm's Overlay network that is somewhat limited in certain providers. Where are you running your cluster?

**Comment by jwalkins2017** [comment]
To add a more context, DFP has a single network assigned to it "Proxy", any container that is behind DFP is also on the "Proxy" network. Is it possible to assign multiple networks to the DFP container and then assign the load balanced containers on those networks? For example:
DFP:
  network
    proxy - external
    internal

Nginx:
  network
    internal

**Comment by vfarcic** [comment]
This project needs adoption. I moved to Kubernetes and cannot dedicate time to this project anymore. Similarly, involvement from other contributors dropped as well. Please consider contributing yourself if you think this project is useful.

**Comment by lleox** [comment]
Dear @jwalkins2017  

If this issue is still relevant, please feel free to leave a comment here.

**Comment by lle0x** [comment]
Closed due to inactivity
