### ISSUE TITLE
Feature - support per-path basic auth configuration with docker labels

### ISSUE THREAD

**Issue by felicienfrancois** [docker-flow/docker-flow-proxy#93]
Basic authentification can currently be setup at a service level using `com.df.users` docker label.

Would be very useful to be able to setup it in a per-path basis using the multiple path mapping pattern:
```yaml
        - com.df.serviceDomain.1=api.qa.myapp.com
        - com.df.servicePath.1=/rest/
        - com.df.serviceDomain.2=www.qa.myapp.com
        - com.df.servicePath.2=/
        - com.df.users.2=myUser:myPassword # currently does not work
```

Use case is protecting frontend of staging environments while keeping API endpoints accessible with their built-in authentication

**Comment by thomasjpfan** [comment]
This is a good idea. One way to implement this is to create a userlist for services that have `com.df.users` defined and use the `http_auth` acl for authentication.

**Comment by vfarcic** [comment]
This project needs adoption. I moved to Kubernetes and cannot dedicate time to this project anymore. Similarly, involvement from other contributors dropped as well. Please consider contributing yourself if you think this project is useful.

**Comment by lleox** [comment]
Dear @felicienfrancois  

If this issue is still relevant, please feel free to leave a comment here.

**Comment by lle0x** [comment]
Closed due to inactivity
