### ISSUE TITLE
Feature - Intrusion Detection

### ISSUE THREAD

**Issue by sstubbs** [docker-flow/docker-flow-proxy#94]
Hi,

I assume this is not in the scope of this project but I am struggling to come up with a viable intrusion detection setup with docker swarm. This project is great and I am currently using it for http. I am thinking to also start using it for TCP. 

Is there some way of banning connections from an ip addresses and if not is there a setup that you might know of to deal with this? Currently I am just running the containers that need it on not in swarm mode with fail2ban and --cap-add=NET_ADMIN but it just seems a bit awkward and I would much rather have one container dealing with this for all containers whether it's the proxy or a container in front or behind it.

**Comment by sstubbs** [comment]
I see there is another feature request https://github.com/docker-flow/docker-flow-proxy/issues/84 which might be able to work with this somehow.

**Comment by vfarcic** [comment]
This project needs adoption. I moved to Kubernetes and cannot dedicate time to this project anymore. Similarly, involvement from other contributors dropped as well. Please consider contributing yourself if you think this project is useful.

**Comment by lleox** [comment]
Dear @sstubbs 

If this issue is still relevant, please feel free to leave a comment here.

**Comment by lle0x** [comment]
Closed due to inactivity
