### ISSUE TITLE
Feature - management web ui

### ISSUE THREAD

**Issue by Jacq** [docker-flow/docker-flow-proxy#95]
Quick question/feature related to the API documentation for the proxy and swarm listener:
* https://proxy.dockerflow.com/usage/
* https://swarmlistener.dockerflow.com/usage/

It would be great a simple web ui (similar to the stats of haproxy) that allows to query and even manage the status of the proxy and swarmlistener service using the above API. It could be a web application living in the swarm listener. Currently I am using the API through the app Postman to debug some situations where some proxies have not been notified of changes, the addition of this kind of ui could bring more insight for newcomers and ease the adoption of DF.

I did not see in the issues/wiki/web any reference to this kind of web ui apart from the raw API, if there is already a project or gist that targets this please point me to it, thanks!

**Comment by vfarcic** [comment]
This project needs adoption. I moved to Kubernetes and cannot dedicate time to this project anymore. Similarly, involvement from other contributors dropped as well. Please consider contributing yourself if you think this project is useful.

**Comment by lleox** [comment]
Dear @Jacq  

If this issue is still relevant, please feel free to leave a comment here.

**Comment by lle0x** [comment]
Closed due to inactivity
