### ISSUE TITLE
WEBDAV support

### ISSUE THREAD

**Issue by paulrobello** [docker-flow/docker-flow-proxy#96]
I am trying to get nextcloud running behind docker-flow-proxy. Everything seems to be working except its complaining about the webdav endpoints not working.
Is there any special configs i should be using to allow webdav?

**Comment by vfarcic** [comment]
I haven't used NextCloud myself so I'm not sure about details. Can you confirm that Overlay network works and that containers in different services can reach each other through it?

**Comment by paulrobello** [comment]
all the normal web related com's look good, it just complaining about webDav, i dont a lot about webDav and was not sure if it needs special treatment on the proxy end

**Comment by vfarcic** [comment]
This project needs adoption. I moved to Kubernetes and cannot dedicate time to this project anymore. Similarly, involvement from other contributors dropped as well. Please consider contributing yourself if you think this project is useful.

**Comment by lleox** [comment]
Dear @paulrobello 

If this issue is still relevant, please feel free to leave a comment here.

**Comment by lle0x** [comment]
Closed due to inactivity
